substitutions:
  _REGION: asia-southeast1
  _SERVICE: bridge-portal-api
  _REPOSITORY: bridge-portal

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$COMMIT_SHA
      - backend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --no-allow-unauthenticated
      - --service-account=bridge-portal-api@$PROJECT_ID.iam.gserviceaccount.com
      - --set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,AUTH_PROVIDER=legacy-firebase,ALLOWED_ORIGINS=http://localhost:3000\,http://localhost:4173\,http://10.18.160.164:3000
      - --update-secrets=FIRESTORE_DATABASE_ID=FIRESTORE_DATABASE_ID:latest
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY